version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: db
      # You should definitely change the password in production
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    networks:
      - edtNetwork
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: symfony serve
    ports:
      - "8000:8000"
    restart: always
    networks:
      - edtNetwork
    depends_on:
      - database

networks:
  edtNetwork:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###